name: barber_app
description: A new Flutter project.

publish_to: 'none'

version: 4.0.0+13

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Packages
  get: ^4.3.8
  get_storage: ^2.0.3
  hive: ^2.0.4
  http: ^0.13.1
  badges: ^3.1.2
  intl: ^0.17.0

  permission_handler: ^8.3.0
  google_fonts: ^2.0.0
  flutter_rating_bar: ^4.0.0
  photo_view: ^0.11.1

  # Firebase
  firebase_auth: ^1.1.0
  firebase_core: ^1.0.3
  google_sign_in: ^5.0.2
  cloud_firestore: ^1.0.5
  firebase_storage: ^8.0.5
  firebase_messaging: ^10.0.3
  awesome_notifications: any

  # Maps / location
  geolocator: ^8.0.1
  google_maps_flutter: ^2.0.6

  # Other utilities
  url_launcher: ^6.0.3
  maps_launcher: ^2.0.0
  file_picker: ^3.0.1
  file_picker_cross: ^4.3.2
  flutter_image_compress: ^1.0.0
  path_provider: ^2.0.1
  uuid: ^3.0.4
  table_calendar: ^3.0.0
  flutter_background: ^1.0.1
  clipboard: ^0.1.3

  # Payment
  flutter_stripe: ^2.0.0
  flutter_credit_card: ^3.0.1

  flutter_inappwebview: ^5.3.2

dependency_overrides:
  disk_space: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # use a recent, null-safe version
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/audio/
    - assets/document/
    - assets/image/
    - assets/gif/
    - assets/video/
    - assets/font/
